# coding: utf-8
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
hdus = fits.open('UGC11680NED01.p_e.rad_SFH_lum_Mass.fits.gz')
img = hdus[0].data
plt.imshow(img)
img = hdus[0].data
plt.imshow(img)
plt.clf()
plt.imshow(img, origin = 'lower')
img.shape
img.min()
mass= img[0,:].cumsum()
plt.figure()
plt.plt(mass)
plt.plot(mass)
mass= img[1,:].cumsum()
plt.plot(mass)
mass= img[2,:].cumsum()
plt.plot(mass)
mass= img[4,:].cumsum()
plt.plot(mass)
mass= img[5,:].cumsum()
plt.plot(mass)
mass= img[6,:].cumsum()
plt.plot(mass)
mass= img[7,:].cumsum()
plt.plot(mass)
mass= img[8,:].cumsum()
plt.plot(mass)
mass= img[9,:].cumsum()
plt.plot(mass)
mass= img[10,:].cumsum()
plt.plot(mass)
mass= img[11,:].cumsum()
plt.plot(mass)
mass= img[15,:].cumsum()
plt.plot(mass)
mass= img[25,:].cumsum()
plt.plot(mass)
mass= img[35,:].cumsum()
plt.plot(mass)
mass= img[0,:].cumsum()
plt.plot(mass)
mass= img[:,:].cumsum()
mass= img[:,:].cumsum()
plt.plot(mass)
mass= img[:,0].cumsum()
plt.plot(mass)
mass= img[:,1].cumsum()
plt.plot(mass)
mass= img[:,2].cumsum()
plt.plot(mass)
mass= img[:,3].cumsum()
plt.plot(mass)
mass= img[:,4].cumsum()
plt.plot(mass)
mass= img[:,5].cumsum()
plt.plot(mass)
mass= img[:,18].cumsum()
plt.plot(mass)
mass= img[:,17].cumsum()
plt.plot(mass)
mass= img[:,18].cumsum()
plt.plot(mass)
mass= img[:,19].cumsum()
plt.plot(mass)
mass= img[:,20].cumsum()
plt.plot(mass)
mass= img[:,21].cumsum()
plt.plot(mass)
mass= img[:,22].cumsum()
plt.plot(mass)
mass= img[:,23].cumsum()
plt.plot(mass)
mass= img[:,24].cumsum()
mass= img[:,24].cumsum()
plt.plot(mass)
mass= img[:,25].cumsum()
plt.plot(mass)
mass= img[:,26].cumsum()
plt.plot(mass)
plt.plot(mass)
mass= img[:,27].cumsum()
plt.plot(mass)
mass= img[:,28].cumsum()
plt.plot(mass)
mass= img[:,29].cumsum()
plt.plot(mass)
mass= img[:,30].cumsum()
plt.plot(mass)
mass= img[:,31].cumsum()
plt.plot(mass)
mass= img[:,32].cumsum()
plt.plot(mass)
mass= img[:,33].cumsum()
plt.plot(mass)
mass= img[:,18].cumsum()
plt.plot(mass)
mass= img[:,19].cumsum()
plt.plot(mass)
mass= img[:,25].cumsum()
plt.plot(mass)
mass= img[:,30].cumsum()
plt.plot(mass)
mass= img[:,30].cumsum()
plt.plot(mass)
mass= img[:,29].cumsum()
plt.plot(mass)
mass= img[:,29].cumsum()
plt.plot(mass)
mass= img[:,28].cumsum()
plt.plot(mass)
mass= img[:,31].cumsum()
plt.plot(mass)
mass= img[:,39].cumsum()
mass= img[:,38].cumsum()
plt.plot(mass)
mass= img[:,37].cumsum()
plt.plot(mass)
mass= img[:,36].cumsum()
plt.plot(mass)
mass= img[:,35].cumsum()
plt.plot(mass)
mass= img[:,34].cumsum()
plt.plot(mass)
mass= img[:,33].cumsum()
plt.plot(mass)
mass= img[:,32].cumsum()
plt.plot(mass)
mass= img[:,31].cumsum()
plt.plot(mass)
mass= img[:,32].cumsum()
plt.plot(mass)
mass= img[:,30].cumsum()
plt.plot(mass)
mass= img[:,29].cumsum()
plt.plot(mass)
